projects:
  app:
    schemPath: src/api/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/api/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
